### ISSUE TITLE
How to determine if robot has reached a particular position.

### ISSUE THREAD

**Issue by abhijeet-sridhar** [EricVoll/RobotDynamicsLibrary#10]
Hey, after enabling the p-controller, is there a way I can check whether the current motion the robot is performing complete or not? I would like to perform certain operations after every time the robot finishes moving its joints to a particular position.

Maybe like a trigger when the particular target position is reached?

**Comment by EricVoll** [comment]
Currently there is no such trigger. The best option would probably be to check the q values coming in from the p-controller and threshold the difference between two sequential joint values.

**Comment by abhijeet-sridhar** [comment]
I was trying out something like this - 

```
public IEnumerator CheckForMotion()
    {
       
        var first = last_q;
        yield return new WaitForSeconds(0.3f);
        var second = last_q;
        Debug.Log(first.SequenceEqual(second));
        
    }
```

But last_q is not returned by the p-controller it is in the RobotBase file itself. How can I get the Q values from the controller?

Ps - The above code always printed true, whether the robot was moving or not.

**Comment by EricVoll** [comment]
Well, the fact that `first.SequenceEqual(...)` prints true makes sense. The controller is always moving and updating. At some point the updates become  tiny, but a p-controller theoretically never reaches the target value. 

Do the following: [here](https://github.com/EricVoll/RobotDynamicsLibrary/blob/a8d50bfe0437765bc247a888c84ddc2865690157/UnityExamples/RobotKinematics/Assets/RobotDynamics/RobotBase.cs#L101) the RobotBase receives the controller's updates. Take these joint values coming in here and check the newest one for the previous one. 

```
double[] prev_joint_values = new double[] {0,0..., 0}
 private void ControlledJointsChanged(object sender, JointsChangedEventArgs e)
    {
        if (!EnablePController) return;

        if (e.DidConverge)
            SetQ(e.joint_values);

        if(prev_joint_values.EqualsWithTolerance(e.joint_values, 0.01))
        {
         // stopped moving.
        }
        prev_joint_values = e.joint_values;
    }
```
For `EqualsWithTolerance` you can use something like [this](https://www.codeproject.com/Answers/1088687/What-is-the-fastest-way-to-compare-two-lists-of-do#answer2)

**Comment by abhijeet-sridhar** [comment]
Hey, I tried using this IsTolerant function - 

```
bool IsTolerant(double[] array1, double[] array2, float tol)
    {
       
        for (int i = 0; i < array1.Length; i++)
        {
            
            double dif = Math.Abs(array1[i] - array2[i]);
            if (dif > tol)
            {
                return false;
            }

        }
       
        return true;
    }
```

And in the controlled joints function, I did this-

```double[] prev_joint_values = new double[] { 0, 0, 0, 0 };
    private void ControlledJointsChanged(object sender, JointsChangedEventArgs e)
    {
        if (!EnablePController) return;

        if (e.DidConverge)
            SetQ(e.joint_values);
        if (IsTolerant(prev_joint_values, e.joint_values, 0.0001f))
        {
            Debug.Log("Not Moving");
        }
        else
        {
            Debug.Log("Moving");
        }
        prev_joint_values = e.joint_values;
    }
```

The console always prints Not Moving, and on printing out the difference, I found that both prev joint values and e.joint_values are always the same. So it never prints that the robot is moving.

**Comment by EricVoll** [comment]
Well, they can't be the same because then the robot wouldn't move. The Unity Console (as far as I remember) usually does not print the full number by default but truncates the output. So maybe check it in the debugger.  There has to be a difference because as I said otherwise the robot would not move. Its only a matter of finding the correct tolerance values. I'd suggest making a public varaible out of your tolerance and then running the game and changing the value of tolerance until it prints correctly.

Instead of using the joint values you could also use the end-effectors position to check if it still moves.
