### ISSUE TITLE
What is the Vector in. AddJoint ('x ', new Vector (0.0, 0.0, 440.0))?

### ISSUE THREAD

**Issue by anan1213095357** [EricVoll/RobotDynamicsLibrary#13]
I added joints to a new object and mounted the script. After setting it up, the result doesn't work. I want to ask what variables need to be filled in and how to operate them specifically?

**Comment by EricVoll** [comment]
The AddJoint method takes two arguments. 
The first is the rotation axis of revolute joints (x,y,z) and the second is the offset vector to the _next_ joint. 

You can look at the example Unity Project which models a Fanuc Robot arm.

**Comment by anan1213095357** [comment]
> The AddJoint method takes two arguments. The first is the rotation axis of revolute joints (x,y,z) and the second is the offset vector to the _next_ joint.
> 
> You can look at the example Unity Project which models a Fanuc Robot arm.

I am creating a normal work from your prefabricated body, but if I create a new parent myself, then create three joints and attach scripts to them. At this point, if IK is enabled, it won't work.

**Comment by EricVoll** [comment]
Without any code I can't help. "It doesn't work" is not helpful for debugging.
