### ISSUE TITLE
Instructions on how to run example

### ISSUE THREAD

**Issue by michael-chikamchun** [EricVoll/RobotDynamicsLibrary#4]
![image](https://user-images.githubusercontent.com/54597149/97195126-59d0ac80-1781-11eb-8dc5-a8f447b32b71.png)
Hi,
I'm trying to run it in unity 2020 and everything is imported correctly. When i move the target in the scene, nothing happens. 
Do we to click the play button? Also, the gif is a little but fuzzy and can't really see all the details in it.
Thank you,
MC

**Comment by michael-chikamchun** [comment]
Nevermind, got it t work thanks :)

**Comment by michael-chikamchun** [comment]
great work btw (y)

**Comment by EricVoll** [comment]
So what was the issue? Is there a problem with the examples?
(Also just for others to read :) )
