### ISSUE TITLE
How to use the joint controller to move to a particular pose.

### ISSUE THREAD

**Issue by abhijeet-sridhar** [EricVoll/RobotDynamicsLibrary#7]
Hi, I have 3 joints in the robot. How can I use the Joint Controller to move the joints to particular pose. For example, I tried using the JointController.ReportNewTargetJointValues function. But for some reason it doesn't happen if i try it more than once. Here is some sample code: 
```
void Update()
 {
  if (Input.GetKeyDown(KeyCode.B))
        {
           double[] safePosition = new double[]{0,0,0};
            CRobot.JointController.ReportNewTargetJointValues(safePosition, true);
            last_q = safePosition;
        }
}
```
When I click on B, the robot returns to the 0,0,0 position. But if I move the joints and press B again, nothing happens.

**Comment by EricVoll** [comment]
The example script using the Fanuc arm shows how to use the controller.
First, you have to subscribe to the controllers event:
```
     //Somewhere e.g. in Awake

     CRobot.AttachJointController(Kp, 0.01f);
     CRobot.JointController.jointsChangedEvent += ControlledJointsChanged;
    

    private void ControlledJointsChanged(object sender, JointsChangedEventArgs e)
    {
        if (!enableController) return;

        if (e.DidConverge)
            SetQ(e.joint_values); //Set Q can be found in the example unity project
    }
```

Then in your `Update` method you have to report time changes to the controller, because the controller has no timer on its own:
`CRobot.JointController.ReportNewFrame(Time.deltaTime);`

If you then move the robot without the inverse kinematics, the joint controllers state does not realize this change and still thinks that your joints are at (0,0,0). So what you would have to do is:
`CRobot.JointController.State.CurrentJointValues = new []{1.0,1,1}` (or whatever your real new joint values are). But currently the State property is private and cannot be accessed. You can fork this repository and make it public, then you can make this change.

**Comment by abhijeet-sridhar** [comment]
Hey, I was still facing some issues trying to make joints move to a particular pose. I am using a controller just like you said above. In my code, I have a function FollowForwardKinematics() - 
```
public void FollowForwardKinematics()
    {
        var positionJoints = _firstQ;
        SetQ(positionJoints);
        _lastQ = positionJoints;
        Robot.JointController.State.CurrentJointValues = positionJoints;
    }
```
Then in the Start method, I have done
```
void Start()
{
    _firstQ = Robot.JointController.State.CurrentJointValues;
}
```
But this doesn't seem to work. For example, I wanted to just make the robot go to its home position after doing some motion using inverse kinematics.

**Comment by EricVoll** [comment]
Hi,
sry for the late reply.

This approach should work if you report the update methods to the controller. Can you post your complete script?

**Comment by abhijeet-sridhar** [comment]
The main problem seems to be that the motion is not happening through the p-controller. The joints instantly move to that position. The actual forward kinematics works but the motion doesn't happen over time.

**Comment by abhijeet-sridhar** [comment]
Hey, I have attached this project that we were discussing about before... Here, in the script MyCustomRobotHandler, I have just the forwardkinematics array to 0, and call the SetQ function. It doesn't move. 
[SampleKinematics.zip](https://github.com/EricVoll/RobotDynamicsLibrary/files/6486733/SampleKinematics.zip)

PS - Haven't really made the state property to public in this attached project. But regardless after the first movement with IK, if I try to use FK, it should work without the jointController knowing about the state. While trying on my project, I took the folder RobotDynamics instead of the DLL. That folder had JointController file and I changed that state to public.

**Comment by EricVoll** [comment]
I just had a quick look at your project. If you disable `EnableInverseKinemativs` and `Enable P Controller`, then click into the game view and then press "A"  it works just fine and the robot snaps to (0,0,0,0). The reason that you have to disable these two is, that the code hat tries to follow the cube constantly calls `SetQ(...)` with other values than 0. Note that `MyCustomRobotHandler` inherits form `RobotBase` so there is more code running in the background.

**Comment by abhijeet-sridhar** [comment]
Ah yes, it snaps to the 0,0,0,0 position as soon as we press A. Also on enabling the p-controller after that, the robot goes back to the position it was already in. Is there a way to apply forward kinematics keeping the controller on? Then instead of snapping, it could move over time just like inverse kinematics works with the controller.

**Comment by EricVoll** [comment]
Yes there is. To do that you have to do one of two things:
- Make this accessable from the outside: [Link to code](https://github.com/EricVoll/RobotDynamicsLibrary/blob/a8d50bfe0437765bc247a888c84ddc2865690157/RobotDynamics/RobotDynamics/JointController/JointController.cs#L80)
- Or just implement your own P-Controller. Its super easy actually. [This method](https://github.com/EricVoll/RobotDynamicsLibrary/blob/a8d50bfe0437765bc247a888c84ddc2865690157/RobotDynamics/RobotDynamics/JointController/JointController.cs#L66) would be all you need.

**Comment by abhijeet-sridhar** [comment]
Oh okay i got it. Thanks a lot for the help :)
