### ISSUE TITLE
Working with Linear Joints

### ISSUE THREAD

**Issue by abhijeet-sridhar** [EricVoll/RobotDynamicsLibrary#8]
Hi, I was trying the linear transformations on my model, but I think I'm missing how to setup the piston. Here is a project with my model and the RobotDynamicsLibrary taken from the Unity example. 

[KinematicsSample.zip](https://github.com/EricVoll/RobotDynamicsLibrary/files/6067879/KinematicsSample.zip)

I have just duplicated a cube here to serve as the piston but the setup seems to be wrong. The joints just go to a weird position on moving the target.

**Comment by EricVoll** [comment]
I'll have a look 👍

**Comment by EricVoll** [comment]
There you go:

The problems were:
- Your robot has a revolute joint and then comes the linear one-> So your definition was wrong
- Since there is a linear joint now, the offsets for the second revolute joint were off as well
- The rotation axes of all revolute joints were wrong

I fixed all of that:
![image](https://user-images.githubusercontent.com/28082576/109638769-b50b1500-7b4e-11eb-95f9-d90ff7a9c69a.png)


[KinematicsSample.zip](https://github.com/EricVoll/RobotDynamicsLibrary/files/6068067/KinematicsSample.zip)

**Comment by abhijeet-sridhar** [comment]
Oh I see. Is there a problem with cube3? It seems to fall off as soon as I run. Also I get a Null Reference in LinearJointHandler in SetJointValue method - 
```
LinearJoint.transform.localPosition = (link.offset + link.linearMotionDirection * q).ToVector3() / RootObject.transform.localScale.x;
```

<img width="1239" alt="Screenshot 2021-03-02 at 4 42 25 PM" src="https://user-images.githubusercontent.com/54523669/109640515-991b6980-7b76-11eb-8161-f266dcfca2ed.png">

**Comment by EricVoll** [comment]
Mhh did you change anything? When I packed in into a zip everything worked nicely. Forward & Backwards

**Comment by EricVoll** [comment]
Mhh did you change anything? When I packed in into a zip everything worked nicely. Forward & Backwards

**Comment by abhijeet-sridhar** [comment]
I just unzipped and ran the scene. I'll try once again

**Comment by EricVoll** [comment]
Sorry I am an idiot. I packed the wrong folder.

**Comment by EricVoll** [comment]
For some reason the zip was much larger now. I only uploaded the Assets folder.

[Assets.zip](https://github.com/EricVoll/RobotDynamicsLibrary/files/6068226/Assets.zip)

**Comment by EricVoll** [comment]
Give me a sec please. I have to create a package... The assets folder alone won't help you much.

**Comment by abhijeet-sridhar** [comment]
I created a new project replaced the assets folder. Seems to work this way.

<img width="1282" alt="Screenshot 2021-03-02 at 4 58 53 PM" src="https://user-images.githubusercontent.com/54523669/109642146-9caff000-7b78-11eb-8765-23df5526c073.png">

**Comment by abhijeet-sridhar** [comment]
Hey, how did you come up with the value .5 in Y axis for the linear joint?
AddLinearJoint(new Vector(0, .5, 0), new Vector(0, 1, 0))

Shouldn't this value just be the nextjoint's pivot - this joint's pistons pivot?

**Comment by EricVoll** [comment]
Hi, 0.5 was just a random offset I came up with. Since the library does not yet support joint value limits, this value can be set to 0 (or any other value) as well.
