### ISSUE TITLE
Problem with horizontal linear joints

### ISSUE THREAD

**Issue by abhijeet-sridhar** [EricVoll/RobotDynamicsLibrary#9]
Hi, I was trying to apply linear joint transformations to horizontal joints that move left/right rather than up/ down. Here is a screenshot of what I'm trying to achieve -

<img width="527" alt="Screenshot 2021-03-20 at 1 36 50 PM" src="https://user-images.githubusercontent.com/54523669/111866054-a1561000-8990-11eb-85e8-8ac4afb91069.png">

I was trying to move Both the joints horizontally left and right, so that it can grip on things. Here is the project - 
[SampleKinematics.zip](https://github.com/EricVoll/RobotDynamicsLibrary/files/6175248/SampleKinematics.zip)

In the scene, there is the model without the gripper, which is disabled. That one works well. The active robot in the scene has 2 extra linear joints for the 2 grippers. The script attached to it is CustomRobotWithGrip.

When I run the scene, the grippers don't move at all. They just get detached and stay in the initial position.

**Comment by EricVoll** [comment]
Hi @abhijeet-sridhar 
In this case this should not be done with linear joints of the inverse kinematics library, but rather with normal scripts that move the GameObject, which should be pretty straight forward to do. Just animate the local position of the gripper-fingers.

**Comment by abhijeet-sridhar** [comment]
Okay sure... I was trying to over-engineer it then :D
